name: Build with PyInstaller

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 更新到最新稳定版

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 明确指定具体版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Clean previous builds
      run: |
        Remove-Item -Recurse -Force dist, build, __pycache__ -ErrorAction SilentlyContinue

    - name: Build main.py (no console)
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: Build music_open.py
      run: |
        pyinstaller --onefile music_open.py

    - name: Verify build output
      run: |
        Get-ChildItem -Path dist -Recurse

    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # 使用最新v4版本
      with:
        name: executables
        path: dist/
