name: Build with PyInstaller

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # 改为你实际使用的版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Clean previous builds
      run: |
        Remove-Item -Recurse -Force dist, build, __pycache__ -ErrorAction SilentlyContinue

    - name: Build main.py (no console)
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: Upload main.exe
      uses: actions/upload-artifact@v4
      with:
        name: main   # 第一个产物的自定义名称
        path: dist/main.exe  # 精确指定文件路径

    - name: Build music_open.py
      run: |
        pyinstaller --onefile music_open.py

    - name: Upload music_open.exe
      uses: actions/upload-artifact@v4
      with:
        name: music  # 第二个产物的自定义名称
        path: dist/music_open.exe
