name: Build with PyInstaller

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest  # 切换到 Windows 环境以支持隐藏终端窗口

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # 指定你的 Python 版本（如 3.8）

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build main.py with PyInstaller (no console)
      run: |
        pyinstaller --onefile --noconsole main.py  # 打包 main.py 并隐藏终端窗口

    - name: Build music_open.py with PyInstaller
      run: |
        pyinstaller --onefile music_open.py  # 打包 music_open.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: dist/
